// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSlot():Promise<string>;

export function GetSlotRole():Promise<string>;

export function PlatformName():Promise<string>;

export function RevealInExplorer(arg1:string):Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowQuit():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
