// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListDir(arg1:string):Promise<Array<main.FileEntry>>;

export function ReadFile(arg1:string):Promise<string>;
