// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.ProjectInput):Promise<main.Project>;

export function Delete(arg1:string):Promise<void>;

export function List():Promise<Array<main.Project>>;

export function ListWithStatus():Promise<Array<main.ProjectStatus>>;

export function MarkUsed(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function Update(arg1:string,arg2:main.ProjectInput):Promise<main.Project>;
