// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['ProjectStore']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['ProjectStore']['Delete'](arg1);
}

export function List() {
  return window['go']['main']['ProjectStore']['List']();
}

export function ListWithStatus() {
  return window['go']['main']['ProjectStore']['ListWithStatus']();
}

export function MarkUsed(arg1) {
  return window['go']['main']['ProjectStore']['MarkUsed'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['ProjectStore']['PickDirectory'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['main']['ProjectStore']['Update'](arg1, arg2);
}
