// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['main']['PtyManager']['Close'](arg1);
}

export function Resize(arg1, arg2, arg3) {
  return window['go']['main']['PtyManager']['Resize'](arg1, arg2, arg3);
}

export function Shutdown() {
  return window['go']['main']['PtyManager']['Shutdown']();
}

export function StartSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['PtyManager']['StartSession'](arg1, arg2, arg3, arg4, arg5);
}

export function Write(arg1, arg2) {
  return window['go']['main']['PtyManager']['Write'](arg1, arg2);
}
