// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Load():Promise<main.Settings>;

export function Save(arg1:main.Settings):Promise<void>;

export function SetConsent(arg1:boolean):Promise<void>;

export function SetSidebarState(arg1:boolean,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;
