// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PruneOld() {
  return window['go']['main']['ClipboardService']['PruneOld']();
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['ClipboardService']['SaveImage'](arg1, arg2);
}
