// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PruneOld():Promise<number>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;
