// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDir(arg1) {
  return window['go']['main']['FileBrowser']['ListDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['FileBrowser']['ReadFile'](arg1);
}
