// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNamed(arg1) {
  return window['go']['main']['LayoutStore']['DeleteNamed'](arg1);
}

export function ListNamed() {
  return window['go']['main']['LayoutStore']['ListNamed']();
}

export function LoadDefault() {
  return window['go']['main']['LayoutStore']['LoadDefault']();
}

export function LoadNamed(arg1) {
  return window['go']['main']['LayoutStore']['LoadNamed'](arg1);
}

export function SaveDefault(arg1) {
  return window['go']['main']['LayoutStore']['SaveDefault'](arg1);
}

export function SaveNamed(arg1) {
  return window['go']['main']['LayoutStore']['SaveNamed'](arg1);
}
