// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNamed(arg1:string):Promise<void>;

export function ListNamed():Promise<Array<main.LayoutSnapshot>>;

export function LoadDefault():Promise<main.LayoutSnapshot>;

export function LoadNamed(arg1:string):Promise<main.LayoutSnapshot>;

export function SaveDefault(arg1:main.LayoutInput):Promise<void>;

export function SaveNamed(arg1:main.LayoutInput):Promise<main.LayoutSnapshot>;
