// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1:string):Promise<void>;

export function Resize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Shutdown():Promise<void>;

export function StartSession(arg1:string,arg2:Array<string>,arg3:string,arg4:number,arg5:number):Promise<string>;

export function Write(arg1:string,arg2:string):Promise<void>;
