// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Load() {
  return window['go']['main']['SettingsStore']['Load']();
}

export function Save(arg1) {
  return window['go']['main']['SettingsStore']['Save'](arg1);
}

export function SetConsent(arg1) {
  return window['go']['main']['SettingsStore']['SetConsent'](arg1);
}

export function SetProxy(arg1, arg2) {
  return window['go']['main']['SettingsStore']['SetProxy'](arg1, arg2);
}

export function SetSidebarState(arg1, arg2) {
  return window['go']['main']['SettingsStore']['SetSidebarState'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['SettingsStore']['SetTheme'](arg1);
}

export function StartWatcher() {
  return window['go']['main']['SettingsStore']['StartWatcher']();
}

export function StopWatcher() {
  return window['go']['main']['SettingsStore']['StopWatcher']();
}
